name: Update README.md file 

on:
  push:
    workflow_dispatch:
      schedule:
        # Tous les jours à 9h du matin (UTC)
        - cron: '00 9 * * *'

jobs:
  update-readme-file:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Update README.md file
        run: node main.js

      - uses: EndBug/add-and-commit@v9
        with:
          author_name: QuentG
          author_email: quentin.gans@outlook.fr
          message: 'README updated by QuentG Bot'